static_transforms:
  - parent: "base_link"
    child: "lidar_link"
    translation: [0.2, 0.0, 0.45]
    rotation_rpy: [0.0, 0.0, 0.0]

  - parent: "base_link"
    child: "imu_link"
    translation: [0.325, 0.0, 0.25]
    rotation_rpy: [0.0, 0.0, 0.0]

  - parent: "base_link"
    child: "gps_link"
    translation: [0.325, 0.0, 0.25]
    rotation_rpy: [0.0, 0.0, 0.0]

  - parent: "base_link"
    child: "camera_link"
    translation: [0.25, 0.0, 0.35]
    rotation_rpy: [0.0, 0.0, 0.0]
